### PR TITLE
Landing_page_salvage

### PR DESCRIPTION
**Pull request by Ibmoore**
## Description
Please include a summary of the change and relevant motivation and context. 
List any dependencies that are required for this change.

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #(issue number 1) #(issue number 2 if applicable)

## How Has This Been Tested?
Please describe in detail how you tested your changes.
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the code etc.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Ibmoore** [comment]
I have checked and certified that the codes comply with the set standards.

**Comment by Ibmoore** [comment]
All good, forge ahead.

**Comment by Ibmoore** [comment]
The codes meet standard and can be merged

**Comment by Ibmoore** [comment]
I am satisfied with this code

**Comment by Ibmoore** [comment]
Approved

**Comment by dsoft02** [comment]
Great job

**Review by dsoft02 — DISMISSED** [review]
Approved ... proceed

**Comment by oluokunkabiru** [comment]
Approved

**Review by oluokunkabiru — DISMISSED** [review]
Nice job

**Review by justice3613 — APPROVED** [review]

**Review by justice3613 — APPROVED** [review]

**Pull request closed without merging**
